# Site settings
title: anton
#email: your-email@domain.com
description: "A small growth today makes progression happen..."
baseurl: ""
url: "www.anton23.com"
twitter_username: antonmaximus
github_username:  antonmaximus

# Build settings
markdown: kramdown
permalink: pretty
