# Site settings
title: anton
email: anton23@gmail.com
description: "A small growth today makes progression happen..."
baseurl: ""
# baseurl: "/mahblog"
url: "www.anton23.com"
twitter_username: antonmaximus
# github_username:  antonmaximus

kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
