# Site settings
title: anton
email: anton23@gmail.com
description: "Be excellent to each other, and... PARTY ON, DUDES!"
#baseurl: ""
baseurl: "/mahblog"
site.baseurl: "/mahblog"
#url: "www.anton23.com"
twitter_username: antonmaximus
# github_username:  antonmaximus

kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:title 
excerpt_separator: ""
