# Site settings
title: anton
#email: your-email@domain.com
description: "A small growth today makes progression happen..."
baseurl: ""
# baseurl: "/mahblog"
url: "www.anton23.com"
twitter_username: antonmaximus
github_username:  antonmaximus

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
permalink: pretty
